// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: milkv-duos-prj

#include "../ui.h"


// COMPONENT ARC1

lv_obj_t * ui_ARC1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ARC1;
    cui_ARC1 = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_ARC1, 150);
    lv_obj_set_height(cui_ARC1, 150);
    lv_obj_set_x(cui_ARC1, -13);
    lv_obj_set_y(cui_ARC1, 13);
    lv_obj_set_align(cui_ARC1, LV_ALIGN_CENTER);
    lv_arc_set_value(cui_ARC1, 75);
    lv_obj_set_style_arc_width(cui_ARC1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_ARC1, lv_color_hex(0x3CD7EC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_ARC1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_ARC1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_ARC1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ARC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ARC1, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ARC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ARC1, -1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ARC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ARC1_NUM);
    children[UI_COMP_ARC1_ARC1] = cui_ARC1;
    lv_obj_add_event_cb(cui_ARC1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ARC1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ARC1_create_hook(cui_ARC1);
    return cui_ARC1;
}

