// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: milkv-duos-prj

#ifndef _UI_COMP_ARC1_H
#define _UI_COMP_ARC1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ARC1
#define UI_COMP_ARC1_ARC1 0
#define _UI_COMP_ARC1_NUM 1
lv_obj_t * ui_ARC1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
