// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: milkv-duos-prj

#ifndef _MILKV_DUOS_PRJ_UI_H
#define _MILKV_DUOS_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label_CPU;
extern lv_obj_t * ui_Arc_CPU_Tem;
extern lv_obj_t * ui_Label_CPU_Tem_Val;
extern lv_obj_t * ui_Label_CPU_Tem;
extern lv_obj_t * ui_Arc_CPU_Usage;
extern lv_obj_t * ui_Label_CPU_Usage_Val;
extern lv_obj_t * ui_Label_CPU_Usage;
extern lv_obj_t * ui_Label_GPU;
extern lv_obj_t * ui_Arc_GPU_Tem;
extern lv_obj_t * ui_Label_GPU_Tem_Val;
extern lv_obj_t * ui_Label_GPU_Tem;
extern lv_obj_t * ui_Arc_GPU_Usage;
extern lv_obj_t * ui_Label_GPU_Usage_Val;
extern lv_obj_t * ui_Label_GPU_Usage;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Arc_GPU_Usage1;
extern lv_obj_t * ui_Label_GPU_Usage_Val1;
extern lv_obj_t * ui_Label_GPU_Usage1;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
